<a href="https://colab.research.google.com/github/Kornel1156/VortexParts/blob/main/2_Pandas_Analiza_Danych/03_Zapis_Odczyt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spis Treści :
0. [Import biblioteki](#a0)
1. [załadowanie danych](#a1)
2. [zapis/odczyt danych z pliku csv ](#a2)
3. [London Bike Dataset](#a3)

### <a name='a0'></a> import biblioteki

In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf

### <a name='a1'></a> Załadowanie danych

In [ ]:
# funkcja ktora pobiera dane z serwisu yahoo finance
def fetch_financial_data(company='FB'):
    """Pobiera dane dotyczące notowań spółki."""
    return yf.download(company)

df = fetch_financial_data()

df.head()

/tmp/ipykernel_901/3907317059.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  return yf.download(company)
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open Volume
Ticker             FB         FB         FB         FB     FB
Date
2026-07-17  44.587002  44.630001  44.500999  44.509998   2100
2026-07-20  44.560001  44.630001  44.560001  44.580002   4100
2026-07-21  44.599998  44.709000  44.599998  44.709000   1000
2026-07-22  44.645000  44.645000  44.320000  44.320000   1500
2026-07-23  44.515999  44.515999  44.490002  44.490002    300

In [ ]:
# spłaszczenie kolumny w yfinance
df.columns = df.columns.get_level_values(0)

### <a name='a2'></a> Zapis/Odczyt z pliku danych

In [ ]:
# wygenerowanie pliku roboczego dla naszych danych
df.to_csv('fb.csv')
# wyeksportowany plik znajduje sie w zakladkach files

In [ ]:
# dane z danego miesiaca
df_nov = df[(df.index.month == 7) & (df.index.year == 2026)]
df_nov

Price           Close       High        Low       Open Volume
Ticker             FB         FB         FB         FB     FB
Date
2026-07-17  44.587002  44.630001  44.500999  44.509998   2100
2026-07-20  44.560001  44.630001  44.560001  44.580002   4100
2026-07-21  44.599998  44.709000  44.599998  44.709000   1000
2026-07-22  44.645000  44.645000  44.320000  44.320000   1500
2026-07-23  44.515999  44.515999  44.490002  44.490002    300
2026-07-24  44.505001  44.650002  44.505001  44.549999   8000
2026-07-27  44.419998  44.492001  44.419998  44.492001   2000
2026-07-28  44.393002  44.529999  44.393002  44.430000   1100
2026-07-29  44.176998  44.176998  44.176998  44.176998    100
2026-07-30  44.455002  44.480000  44.450001  44.470001    700
2026-07-31  44.570000  44.610001  44.520000  44.529999  10300

In [ ]:
# zapisanie danych do pliku
df_nov.to_csv('fb_nov.csv')

In [ ]:
# wczytanie danych z pliku
new_df = pd.read_csv('fb_nov.csv')
new_df

,Price,Close,High,Low,Open,Volume
0,Ticker,FB,FB,FB,FB,FB
1,Date,NaN,NaN,NaN,NaN,NaN
2,2026-07-17,44.58700180053711,44.630001068115234,44.500999450683594,44.5099983215332,2100
3,2026-07-20,44.560001373291016,44.630001068115234,44.560001373291016,44.58000183105469,4100
4,2026-07-21,44.599998474121094,44.70899963378906,44.599998474121094,44.70899963378906,1000
5,2026-07-22,44.64500045776367,44.64500045776367,44.31999969482422,44.31999969482422,1500
6,2026-07-23,44.51599884033203,44.51599884033203,44.4900016784668,44.4900016784668,300
7,2026-07-24,44.505001068115234,44.650001525878906,44.505001068115234,44.54999923706055,8000
8,2026-07-27,44.41999816894531,44.492000579833984,44.41999816894531,44.492000579833984,2000
9,2026-07-28,44.393001556396484,44.529998779296875,44.393001556396484,44.43000030517578,1100
10,2026-07-29,44.176998138427734,44.176998138427734,44.176998138427734,44.176998138427734,100
11,2026-07-30,44.45500183105469,44.47999954223633,44.45000076293945,44.470001220703125,700
12,2026-07-31,44.56999969482422,44.61000061035156,44.52000045776367,44.529998779296875,10300

In [ ]:
# zapis danych do formatu pliku excel
df_nov.to_excel('fb_nov.xlsx')

In [ ]:
# wczytanie danych z pliku o fromacie excel
new_df = pd.read_excel('fb_nov.xlsx')
new_df
# ale uwaga data została wczytana jako kolumna a nie sam w sobie index jak poprzednio

                  Price      Close       High        Low       Open Volume
0                Ticker         FB         FB         FB         FB     FB
1                  Date        NaN        NaN        NaN        NaN    NaN
2   2026-07-17 00:00:00  44.587002  44.630001  44.500999  44.509998   2100
3   2026-07-20 00:00:00  44.560001  44.630001  44.560001  44.580002   4100
4   2026-07-21 00:00:00  44.599998     44.709  44.599998     44.709   1000
5   2026-07-22 00:00:00     44.645     44.645      44.32      44.32   1500
6   2026-07-23 00:00:00  44.515999  44.515999  44.490002  44.490002    300
7   2026-07-24 00:00:00  44.505001  44.650002  44.505001  44.549999   8000
8   2026-07-27 00:00:00  44.419998  44.492001  44.419998  44.492001   2000
9   2026-07-28 00:00:00  44.393002  44.529999  44.393002      44.43   1100
10  2026-07-29 00:00:00  44.176998  44.176998  44.176998  44.176998    100
11  2026-07-30 00:00:00  44.455002      44.48  44.450001  44.470001    700
12  2026-07-31 00:00:00      44.57  44.610001      44.52  44.529999  10300

In [ ]:
# dlatego musimy sobie ustawic kolumne daty jako index poprzez parametr index
new_df = pd.read_excel('fb_nov.xlsx' , index_col=0)
# data staje sie indeksem naszej tabeli
new_df

                         Close       High        Low       Open Volume
Price
Ticker                      FB         FB         FB         FB     FB
Date                       NaN        NaN        NaN        NaN    NaN
2026-07-17 00:00:00  44.587002  44.630001  44.500999  44.509998   2100
2026-07-20 00:00:00  44.560001  44.630001  44.560001  44.580002   4100
2026-07-21 00:00:00  44.599998     44.709  44.599998     44.709   1000
2026-07-22 00:00:00     44.645     44.645      44.32      44.32   1500
2026-07-23 00:00:00  44.515999  44.515999  44.490002  44.490002    300
2026-07-24 00:00:00  44.505001  44.650002  44.505001  44.549999   8000
2026-07-27 00:00:00  44.419998  44.492001  44.419998  44.492001   2000
2026-07-28 00:00:00  44.393002  44.529999  44.393002      44.43   1100
2026-07-29 00:00:00  44.176998  44.176998  44.176998  44.176998    100
2026-07-30 00:00:00  44.455002      44.48  44.450001  44.470001    700
2026-07-31 00:00:00      44.57  44.610001      44.52  44.529999  10300

### <a name='a3'></a> London Bike Dataset